<p>Make sure you create and assign your menus to the menu locations found in the theme.</p>

<p><strong>Missing items in your menu?</strong> Make sure you have added pages that are automatically generated by Easy Digital Downloads and any applicable plugins.</p>

<p><a href="<?php echo get_template_directory_uri(); ?>/inc/setup/images/setup-menus.gif">
	<img src="<?php echo get_template_directory_uri(); ?>/inc/setup/images/setup-menus.gif" width="430" alt="" />
</a></p>

<p><a href="<?php echo admin_url( 'nav-menus.php?action=locations' ); ?>" class="button button-primary button-large">Manage Menus</a></p>
